name: 上游同步

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天执行
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: 从上游同步最新提交
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 步骤 1：运行标准的检出操作
      - name: 检出目标仓库
        uses: actions/checkout@v3

      # 步骤 2：保存本地更改
      - name: 保存本地更改
        run: |
          git stash save "本地更改"

      # 步骤 3：添加上游远程仓库并拉取变更
      - name: 同步上游变更
        run: |
          git remote add upstream https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git
          git fetch upstream main

          # 使用 merge 合并上游变更，确保使用 "--no-commit" 选项以允许后续修改
          git merge --no-commit upstream/main

          # 跳过合并中的多个指定文件
          # git checkout -- path/to/skip/file1
          # git checkout -- path/to/skip/file2
          # git checkout -- path/to/skip/file3

          # 提交合并
          git commit -m "合并上游变更"

      # 步骤 4：应用保存的本地更改
      - name: 恢复本地更改
        run: |
          git stash pop

      # 步骤 5：检查同步是否失败
      - name: 同步检查
        if: failure()
        run: |
          echo "[错误] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新。您需要手动同步您的分支。请参阅详细教程：https://github.com/Yidadaa/ChatGPT-Next-Web#enable-automatic-updates"
          exit 1

