name: 与上游同步

on:
  schedule:
    - cron: "0 0 * * *" # 每天执行
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: 与上游同步
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 添加上游远程仓库
        run: git remote add upstream https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git

      - name: 获取上游仓库的最新更改
        run: git fetch upstream main

      - name: 保存本地修改
        run: git stash save "本地修改"
        
      - name: 设置 Git 用户信息
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"

      - name: 合并上游仓库的更改，允许后续修改
        run: git merge --no-commit --allow-unrelated-histories upstream/main

      - name: 跳过合并中的指定文件
        run: |
          git checkout -- .github/workflows/main.yml

      - name: 提交合并的更改
        run: git commit -m "合并上游仓库的更改"

      - name: 恢复本地变更
        run: |
          if git rev-parse --verify refs/stash; then
            git stash pop
          else
            echo "No stash entries found."
          fi

      - name: 将更改推送到 origin 仓库
        run: git push origin main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
