name: Upstream Sync Custom

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: 从上游同步最新提交
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 步骤1：运行标准的检出操作
      - name: 检出目标存储库
        uses: actions/checkout@v3

      # 步骤2：获取上游更改
      - name: 获取上游更改
        run: git fetch upstream main

      # 步骤3：从上游合并更改
      - name: 从上游合并更改
        run: git merge upstream/main

      # 步骤4：处理合并冲突（可选）
      - name: 处理合并冲突
        run: |
          git diff --name-only --diff-filter=U | xargs -I {} git checkout --ours "{}"
          git add .
          git commit -m "通过选择我们的更改解决合并冲突"

      # 步骤5：将更改推送到分叉存储库
      - name: 将更改推送到分叉存储库
        run: git push origin main
